export const FACULITY_SELF_EVALUATION_SUBMIT_ASYNC =
  "FACULITY_SELF_EVALUATION_SUBMIT_ASYNC";
export const FACULITY_SELF_EVALUATION_SUBMIT_ATTEMPT =
  "FACULITY_SELF_EVALUATION_SUBMIT_ATTEMPT";
export const FACULITY_SELF_EVALUATION_SUBMIT_SUCCESS =
  "FACULITY_SELF_EVALUATION_SUBMIT_SUCCESS";
export const FACULITY_SELF_EVALUATION_SUBMIT_FAILURE =
  "FACULITY_SELF_EVALUATION_SUBMIT_FAILURE";
export const RESET_FACULITY_SELF_EVALUATION = "RESET_FACULITY_SELF_EVALUATION";

export const CHAIR_SELF_EVALUATION_SUBMIT_ASYNC =
  "CHAIR_SELF_EVALUATION_SUBMIT_ASYNC";
export const CHAIR_SELF_EVALUATION_SUBMIT_ATTEMPT =
  "CHAIR_SELF_EVALUATION_SUBMIT_ATTEMPT";
export const CHAIR_SELF_EVALUATION_SUBMIT_SUCCESS =
  "CHAIR_SELF_EVALUATION_SUBMIT_SUCCESS";
export const CHAIR_SELF_EVALUATION_SUBMIT_FAILURE =
  "CHAIR_SELF_EVALUATION_SUBMIT_FAILURE";
export const CHAIR_SELF_EVALUATION_SUBMIT_RESET =
  "CHAIR_SELF_EVALUATION_SUBMIT_RESET";

export const SCHOOL_EVALUATION_SUBMIT_ASYNC = "SCHOOL_EVALUATION_SUBMIT_ASYNC";
export const SCHOOL_EVALUATION_SUBMIT_SUCCESS =
  "SCHOOL_EVALUATION_SUBMIT_SUCCESS";
export const SCHOOL_EVALUATION_SUBMIT_FAILURE =
  "SCHOOL_EVALUATION_SUBMIT_FAILURE";
export const SCHOOL_EVALUATION_SUBMIT_ATTEMPT =
  "SCHOOL_EVALUATION_SUBMIT_ATTEMPT";
export const SCHOOL_EVALUATION_SUBMIT_RESET = "SCHOOL_EVALUATION_SUBMIT_RESET";
