export const FACULITY_SELF_EVALUATION_SUBMIT_ASYNC =
  "FACULITY_SELF_EVALUATION_SUBMIT_ASYNC";
export const FACULITY_SELF_EVALUATION_SUBMIT_ATTEMPT =
  "FACULITY_SELF_EVALUATION_SUBMIT_ATTEMPT";
export const FACULITY_SELF_EVALUATION_SUBMIT_SUCCESS =
  "FACULITY_SELF_EVALUATION_SUBMIT_SUCCESS";
export const FACULITY_SELF_EVALUATION_SUBMIT_FAILURE =
  "FACULITY_SELF_EVALUATION_SUBMIT_FAILURE";
export const RESET_FACULITY_SELF_EVALUATION = "RESET_FACULITY_SELF_EVALUATION";
