//fetch users
export const FETCH_USERS_ASYNC = "FETCH_USERS_ASYNC";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_RESET = "FETCH_USERS_RESET";

// change roles
export const CHANGE_ROLE_ASYNC = "CHANGE_ROLE_ASYNC";
export const CHANGE_ROLE_SUCCESS = "CHANGE_ROLE_SUCCESS";
export const CHANGE_ROLE_FAILURE = "CHANGE_ROLE_FAILURE";
export const CHANGE_ROLE_RESET = "CHANGE_ROLE_RESET";
