export const UPDATE_PROFILE_ASYNC = "UPDATE_PROFILE_ASYNC";
export const UPDATE_PROFILE_ATTEMPT = "UPDATE_PROFILE_ATTEMPT";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const RESET_UPDATE_PROFILE = "RESET_UPDATE_PROFILE"